config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  resources :users do 
    resources :buildings
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/session', to: 'sessions#destroy'
  post '/projects', to: 'projects#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :projects
    has_many :users, through: :projects
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :building
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :projects
    has_many :buildings, through: :projects

    accepts_nested_attributes_for :buildings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user, :require_login, :admin_only

  def current_user
    if session[:user_id].present?
      user = User.find_by(:id => session[:user_id])
    end
  end

  def require_login
    unless current_user
      redirect_to root_url
    end
  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
    def index
        if params[:user_id] 
            @buildings = User.find(params[:user_id]).buildings
        else
            @buildings = Building.all
        end
    end

    def new
        @user = User.find(params[:user_id])
        @building = Building.new
    end

    def create
        @building = Building.new(building_params)
        @user = User.find(params[:user_id])
        if @building.save
            @user.buildings << @building
            redirect_to user_buildings_path
        else
            render :new
        end
    end

    def show
        @building = Building.find(params[:id])
        @user = User.find(params[:id])

    end

    private
    def building_params
        params.require(:building).permit(:name, :address, :floors)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = User.find_by(:username => params[:user][:username])
        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to user_path(user)
        else
          flash[:alert] = "Wrong Password. Please try again"
          render :new
        end
    end

    def destroy
        if current_user
            session.delete :user_id
            redirect_to root_url
        end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]
    def new
       @user = User.new
    end

    def create
        user = User.create(user_params)
        if user.valid?
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end
    
    private
    def user_params
        params.require(:user).permit(:name, :trade, :username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buildings/_form.html.erb
<%= form_for [user, building] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br />
    <%= f.label :address %>
    <%= f.text_field :address %><br />
    <%= f.label :floors %>
    <%= f.number_field :floors %><br />
    <br />
    <%= f.submit %>
<% end %>

app/views/buildings/edit.html.erb
<h1>Edit Buiding</h1>
<%= render partial: 'form', locals: {user: @user, buiding: @building} %>

app/views/buildings/index.html.erb
<h1>Buildings</h1>
<% if current_user %>
  <ul>
  <% current_user.buildings.each do |building| %>
    <li><%= link_to "#{building.name}" %>#, #user_building_path(building) %></li>
  <% end %>
  </ul>
  
<% end %>

app/views/buildings/new.html.erb
<h1>New Building</h1>
<%= render partial: 'form', locals: {building: @building, user: @user} %>

app/views/buildings/show.html.erb
<h1><%= @building.name %></h1>
Adress: <%= @building.address %><br />
Number of Floors: <%= @building.floors %><br />
<br />
<%= form_tag("/projects", method: "post") do %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<%= hidden_field_tag :building_id, @building.id %>
<%= button_tag "Save Building" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EngineeringManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% if !current_user %>
          <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
          <%= link_to "Log in", login_path, class:"navbar-brand" %>
        <% end %>
        <% if current_user %>
          <%= link_to "#{current_user.name}'s profile", user_path(current_user), class:"navbar-brand"%>
          <%= link_to "Log Out", session_url, class:"navbar-brand",method:'delete' %>
        <% end %>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
    <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div>
<div style='width: 600px;margin:auto'>
  <img  style='width: 600px' src="https://img.theculturetrip.com/1440x807/smart/wp-content/uploads/2016/08/tct-build-111.jpg">
</div>
<h1 align="center">Welcome to Your Building Manager!</h1>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br />
    <%= f.label :trade %>
    <%= f.select :trade, ['Electrical', 'Mechanical', 'Plumbing & FP']%>
    <%= f.label :username %>
    <%= f.text_field :username %><br />
    Password: <%= f.password_field :password %>
    Password Confirmation: <%= f.password_field :password_confirmation %>
    <br />
    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %></h1>
<p>Trade: <%= @user.trade %></p>


<%= link_to "See your Buildings", user_buildings_path(@user) %>
<%= link_to "Add a New Building", new_user_building_path(@user) %>